# Generated by Django 6.1.1 on 2026-09-17 15:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoInicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip', models.GenericIPAddressField(db_index=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'intento de inicio de sesión',
                'verbose_name_plural': 'intentos de inicio de sesión',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('juridica', 'Jurídica'), ('tecnica', 'Técnica'), ('financiera', 'Financiera')], max_length=20)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='cuentas.entidad')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ['entidad__nombre', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='cuentas.area'),
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('accion', models.CharField(db_index=True, max_length=80)),
                ('objeto_tipo', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=64)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('rol', models.CharField(choices=[('admin_entidad', 'Administrador de entidad'), ('jefe_area', 'Jefe de área'), ('evaluador', 'Evaluador'), ('consulta', 'Consulta')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('areas', models.ManyToManyField(blank=True, to='cuentas.area')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='cuentas.entidad')),
                ('invitada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitación',
                'verbose_name_plural': 'invitaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('entidad', 'tipo'), name='area_unica_por_entidad'),
        ),
    ]
