# Generated by Django 6.1.1 on 2026-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_intentoiniciosesion_area_usuario_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_activo',
            field=models.BooleanField(default=False, verbose_name='2FA activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secreto',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
