# Generated by Django 6.1.1 on 2026-09-17 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuentas', '0003_usuario_totp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoSoporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='usuario_entidad_segun_rol',
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='rol',
            field=models.CharField(choices=[('admin_entidad', 'Administrador de entidad'), ('jefe_area', 'Jefe de área'), ('evaluador', 'Evaluador'), ('consulta', 'Consulta'), ('soporte', 'Soporte LeMarTek')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin_entidad', 'Administrador de entidad'), ('jefe_area', 'Jefe de área'), ('evaluador', 'Evaluador'), ('consulta', 'Consulta'), ('soporte', 'Soporte LeMarTek')], default='evaluador', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rol__in', ['superadmin', 'soporte']), ('entidad__isnull', True)), models.Q(models.Q(('rol__in', ['superadmin', 'soporte']), _negated=True), ('entidad__isnull', False)), _connector='OR'), name='usuario_entidad_segun_rol'),
        ),
        migrations.AddField(
            model_name='accesosoporte',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_soporte', to='cuentas.entidad'),
        ),
        migrations.AddField(
            model_name='accesosoporte',
            name='otorgado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesosoporte',
            name='soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_soporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
