# Generated by Django 6.1.1 on 2026-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_acceso_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False, verbose_name='debe cambiar la contraseña'),
        ),
        migrations.DeleteModel(
            name='Invitacion',
        ),
    ]
