# Generated by Django 6.1.1 on 2026-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0005_usuario_debe_cambiar_clave_delete_invitacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoauditoria",
            name="huella",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="usuario",
            name="compromiso_aceptado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="compromiso_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
