# Generated by Django 6.1.1 on 2026-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auditoria_inmutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='exigir_microsoft',
            field=models.BooleanField(default=False, verbose_name='solo acceso con Microsoft'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='microsoft_directorio',
            field=models.CharField(blank=True, max_length=36, verbose_name='directorio de Microsoft'),
        ),
    ]
