# Generated by Django 6.1.1 on 2026-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_acceso_microsoft'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='microsoft_crear_usuarios',
            field=models.BooleanField(default=False, verbose_name='crear usuarios al entrar con Microsoft'),
        ),
    ]
