# Generated by Django 6.1.1 on 2026-10-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_microsoft_crear_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='modulo_ops',
            field=models.BooleanField(default=False, verbose_name='módulo de prestación de servicios'),
        ),
    ]
