# Generated by Django 6.1.1 on 2026-10-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auditoria_sin_truncate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='onedrive_autorizado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OneDrive autorizado'),
        ),
    ]
