# Generated by Django 6.1.1 on 2026-09-17 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0003_usuario_totp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80)),
                ('fecha_cierre', models.DateField()),
                ('objeto', models.TextField(blank=True)),
                ('documento_base', models.JSONField()),
                ('carpeta_drive', models.CharField(blank=True, max_length=500)),
                ('proponentes_no_reconocidos', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('juridica', 'Jurídica'), ('tecnica', 'Técnica'), ('financiera', 'Financiera')], max_length=20)),
                ('estado', models.CharField(choices=[('sin_asignar', 'Sin asignar'), ('asignada', 'Asignada'), ('evaluando', 'Evaluando'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada')], default='sin_asignar', max_length=20)),
                ('asignada_en', models.DateTimeField(blank=True, null=True)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluaciones.proceso')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.PositiveIntegerField()),
                ('hoja', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_archivo', models.CharField(max_length=500)),
                ('drive_file_id', models.CharField(max_length=200)),
                ('advertencia', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponentes', to='evaluaciones.proceso')),
            ],
            options={
                'ordering': ['numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requisito', models.PositiveSmallIntegerField()),
                ('datos', models.JSONField()),
                ('requiere_revision', models.BooleanField()),
                ('evaluado_en', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.proponente')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requisito', models.PositiveSmallIntegerField()),
                ('cumple', models.BooleanField()),
                ('nota', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='evaluaciones.proponente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='proceso',
            constraint=models.UniqueConstraint(fields=('entidad', 'codigo'), name='proceso_codigo_unico_por_entidad'),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(fields=('proceso', 'tipo'), name='evaluacion_tipo_unico_por_proceso'),
        ),
        migrations.AddConstraint(
            model_name='proponente',
            constraint=models.UniqueConstraint(fields=('proceso', 'hoja'), name='proponente_hoja_unica'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'proponente', 'requisito'), name='resultado_unico'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'proponente', 'requisito'), name='revision_unica'),
        ),
    ]
