# Generated by Django 6.1.1 on 2026-09-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuario_totp'),
        ('evaluaciones', '0002_aislamiento_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('latido', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('en_fila', 'En fila'), ('procesando', 'Procesando'), ('terminado', 'Terminado'), ('error', 'Error'), ('cancelado', 'Cancelado')], db_index=True, default='en_fila', max_length=20)),
                ('turno', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('latido', models.DateTimeField(blank=True, null=True)),
                ('trabajador', models.CharField(blank=True, max_length=120)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='evaluaciones.proponente')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['estado', 'turno', 'creado_en'], name='trabajo_orden_fila')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['en_fila', 'procesando'])), fields=('evaluacion', 'proponente'), name='trabajo_pendiente_unico')],
            },
        ),
    ]
