# Generated by Django 6.1.1 on 2026-09-17 16:29

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuario_totp'),
        ('evaluaciones', '0003_fila_de_trabajos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInforme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('juridica', 'Jurídica'), ('tecnica', 'Técnica'), ('financiera', 'Financiera')], max_length=20)),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_plantilla)),
                ('mapeo', models.JSONField()),
                ('activa', models.BooleanField(default=True)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='cuentas.entidad')),
                ('subida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subida_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('entidad', 'tipo'), name='plantilla_activa_unica')],
            },
        ),
    ]
