# Generated by Django 6.1.1 on 2026-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_plantillas_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillainforme',
            name='inspeccion',
            field=models.JSONField(default=dict),
        ),
    ]
