# Generated by Django 6.1.1 on 2026-09-17 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_usuario_totp'),
        ('evaluaciones', '0006_plantilla_inspeccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('juridica', 'Jurídica'), ('tecnica', 'Técnica'), ('financiera', 'Financiera')], max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('definicion', models.JSONField()),
                ('nota', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_evaluacion', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluaciones.plantillaevaluacion'),
        ),
        migrations.AddConstraint(
            model_name='plantillaevaluacion',
            constraint=models.UniqueConstraint(fields=('entidad', 'tipo', 'version'), name='plantilla_evaluacion_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='plantillaevaluacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('entidad', 'tipo'), name='plantilla_evaluacion_activa_unica'),
        ),
    ]
