# Generated by Django 6.1.1 on 2026-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_plantillas_evaluacion_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='documentos_eliminados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
