# Generated by Django 6.1.1 on 2026-09-17 17:09

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_acceso_soporte'),
        ('evaluaciones', '0009_retencion_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaVerificada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('proponente', 'Proponente'), ('representante_legal', 'Representante legal'), ('suplente', 'Representante legal suplente'), ('integrante', 'Integrante del consorcio o unión temporal')], max_length=30)),
                ('tipo', models.CharField(choices=[('natural', 'Persona natural'), ('juridica', 'Persona jurídica')], max_length=10)),
                ('nombre', models.CharField(max_length=300)),
                ('documento', models.CharField(max_length=30)),
                ('fecha_expedicion_documento', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='evaluaciones.personaverificada')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='evaluaciones.proponente')),
            ],
            options={
                'ordering': ['creada_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAportado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisito', models.PositiveSmallIntegerField()),
                ('fecha_expedicion', models.DateField()),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_aportado)),
                ('observacion', models.TextField(blank=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_aportados', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_aportados', to='evaluaciones.proponente')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='evaluaciones.personaverificada')),
            ],
            options={
                'ordering': ['subido_en'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('archivo', models.FileField(blank=True, max_length=300, upload_to=evaluaciones.models._ruta_expediente)),
                ('tamano', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='evaluaciones.evaluacion')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'version'), name='expediente_version_unica')],
            },
        ),
    ]
