# Generated by Django 6.1.1 on 2026-09-18 05:06

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_usuario_debe_cambiar_clave_delete_invitacion'),
        ('evaluaciones', '0011_personas_aportados_expediente_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='ajustes_pliego',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AnalisisPliego',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_pliego)),
                ('paginas', models.PositiveIntegerField()),
                ('documento_tipo', models.CharField(blank=True, max_length=80)),
                ('extraccion', models.JSONField()),
                ('version', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='analisis_pliego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='evaluaciones.analisispliego'),
        ),
        migrations.AddConstraint(
            model_name='analisispliego',
            constraint=models.UniqueConstraint(fields=('entidad', 'sha256'), name='pliego_unico_por_entidad'),
        ),
    ]
