# Generated by Django 6.1.1 on 2026-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0013_analisis_pliego_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaverificada',
            name='detectada',
            field=models.BooleanField(default=False),
        ),
    ]
