# Generated by Django 6.1.1 on 2026-09-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0014_persona_detectada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('ano', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='año')),
                ('valor', models.PositiveIntegerField()),
                ('norma', models.CharField(blank=True, max_length=200)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'salario mínimo',
                'verbose_name_plural': 'salarios mínimos',
                'ordering': ['-ano'],
            },
        ),
    ]
