# Generated by Django 6.1.1 on 2026-09-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0016_salario_minimo_valores'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisispliego',
            name='error_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='estado_ia',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='ia_iniciada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='ia_terminada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='modelo_ia',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='progreso_ia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='requisitos_ia',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='version_ia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
