# Generated by Django 6.1.1 on 2026-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0017_lectura_ia_pliego'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='parametros_tecnicos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
