# Generated by Django 6.1.1 on 2026-09-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0018_parametros_tecnicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionRendimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
                ('nota', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
