# Generated by Django 6.1.1 on 2026-09-23 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0020_parametros_financieros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisispliego',
            name='confirmados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='confirmados_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='parametros_confirmados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='parametros_ia',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analisispliego',
            name='version_parametros_ia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
