# Generated by Django 6.1.1 on 2026-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0021_analisispliego_confirmados_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='matriz2',
            field=models.FileField(blank=True, max_length=300, upload_to='matrices/'),
        ),
    ]
