# Generated by Django 6.1.1 on 2026-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0022_proceso_matriz2'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisispliego',
            name='requisitos_asumidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
