# Generated by Django 6.1.1 on 2026-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_usuario_debe_cambiar_clave_delete_invitacion'),
        ('evaluaciones', '0023_analisispliego_requisitos_asumidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoNoAutomatizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('requisito', models.TextField()),
                ('cita', models.TextField(blank=True)),
                ('clase', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('veces', models.PositiveIntegerField(default=0)),
                ('veces_asumido', models.PositiveIntegerField(default=0)),
                ('procesos', models.JSONField(blank=True, default=list)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('verificacion', models.CharField(blank=True, max_length=60)),
                ('nota', models.TextField(blank=True)),
                ('entidades', models.ManyToManyField(blank=True, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-veces_asumido', '-veces'],
                'indexes': [models.Index(fields=['-veces'], name='evaluacione_veces_2f5a4d_idx'), models.Index(fields=['clase'], name='evaluacione_clase_ddba7e_idx')],
            },
        ),
    ]
