# Generated by Django 6.1.1 on 2026-09-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0024_requisitonoautomatizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaDeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=60)),
                ('ambito', models.CharField(max_length=12)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('ejemplo', models.TextField(blank=True)),
                ('veces', models.PositiveIntegerField(default=0)),
                ('ofertas', models.PositiveIntegerField(default=0)),
                ('procesos', models.JSONField(blank=True, default=list)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('nota', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-ofertas', '-veces'],
                'constraints': [models.UniqueConstraint(fields=('clave', 'area'), name='causa_unica_por_area')],
            },
        ),
    ]
