# Generated by Django 6.1.1 on 2026-09-27 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0006_cumplimiento_legal"),
        ("evaluaciones", "0025_causaderevision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="modelos_ia",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="version_sistema",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="proceso",
            name="archivado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proceso",
            name="archivado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultado",
            name="trazabilidad",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MuestraControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("semilla", models.BigIntegerField()),
                ("parametros", models.JSONField(default=dict)),
                ("ofertas_sorteadas", models.JSONField(default=list)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_curso", "En curso"),
                            ("con_hallazgos", "Con hallazgos"),
                            ("cerrada", "Cerrada conforme"),
                            ("anulada", "Anulada"),
                        ],
                        default="en_curso",
                        max_length=20,
                    ),
                ),
                ("requisitos_ampliados", models.JSONField(default=list)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("cerrada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cerrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cuentas.entidad",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muestras",
                        to="evaluaciones.evaluacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="AdopcionPuntaje",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("puntaje", models.FloatField()),
                ("detalle", models.JSONField(default=dict)),
                ("nota", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now=True)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cuentas.entidad",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adopciones_puntaje",
                        to="evaluaciones.evaluacion",
                    ),
                ),
                (
                    "proponente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="evaluaciones.proponente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evaluacion", "proponente"),
                        name="adopcion_puntaje_unica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemMuestra",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("requisito", models.PositiveSmallIntegerField()),
                ("usa_ia", models.BooleanField(default=False)),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conforme", "Conforme"),
                            ("no_conforme", "No conforme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                ("soporte_visto", models.BooleanField(default=False)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cuentas.entidad",
                    ),
                ),
                (
                    "proponente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="evaluaciones.proponente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "muestra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="evaluaciones.muestracontrol",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("muestra", "proponente", "requisito"),
                        name="item_muestra_unico",
                    )
                ],
            },
        ),
    ]
