# Generated by Django 6.1.1 on 2026-10-03 00:25

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auditoria_inmutable'),
        ('evaluaciones', '0027_cumplimiento_legal_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('juridica', 'Jurídica'), ('tecnica', 'Técnica'), ('financiera', 'Financiera')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('palabras_clave', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencias', to='cuentas.entidad')),
                ('jefes', models.ManyToManyField(blank=True, related_name='dependencias_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='dependencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluaciones.dependencia'),
        ),
        migrations.CreateModel(
            name='DesignacionComite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consecutivo', models.CharField(max_length=40)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('dependencia', models.CharField(blank=True, max_length=200)),
                ('miembros', models.JSONField(default=list)),
                ('designado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_designacion)),
                ('sha256', models.CharField(max_length=64)),
                ('designado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='evaluaciones.evaluacion')),
            ],
            options={
                'ordering': ['-designado_en'],
            },
        ),
        migrations.CreateModel(
            name='MiembroComite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('designado_en', models.DateTimeField(auto_now_add=True)),
                ('retirado_en', models.DateTimeField(blank=True, null=True)),
                ('designado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite', to='evaluaciones.evaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['designado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoProponente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desde', models.DateTimeField(auto_now_add=True)),
                ('latido', models.DateTimeField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='evaluaciones.proponente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'proponente'), name='bloqueo_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='dependencia',
            constraint=models.UniqueConstraint(fields=('entidad', 'tipo', 'nombre'), name='dependencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='designacioncomite',
            constraint=models.UniqueConstraint(fields=('entidad', 'consecutivo'), name='designacion_consecutivo_unico'),
        ),
    ]
