# Generated by Django 6.1.1 on 2026-10-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0029_estructura_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacioncomite',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designaciones', to='evaluaciones.evaluacion'),
        ),
    ]
