# Generated by Django 6.1.1 on 2026-10-03 02:31

import django.db.models.deletion
import evaluaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auditoria_inmutable'),
        ('evaluaciones', '0031_comite_desde_responsables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaRevisionCruzada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consecutivo', models.CharField(max_length=40)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('resumen', models.JSONField(default=dict)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_acta_cruzada)),
                ('sha256', models.CharField(max_length=64)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('generada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_revision_cruzada', to='evaluaciones.proceso')),
            ],
            options={
                'ordering': ['-generada_en'],
                'constraints': [models.UniqueConstraint(fields=('entidad', 'consecutivo'), name='acta_cruzada_consecutivo_unico')],
            },
        ),
    ]
