# Generated by Django 6.1.1 on 2026-10-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auditoria_inmutable'),
        ('evaluaciones', '0033_acta_revision_cruzada_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefijo', models.CharField(max_length=10)),
                ('anio', models.PositiveSmallIntegerField()),
                ('ultimo', models.PositiveIntegerField(default=0)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entidad', 'prefijo', 'anio'), name='consecutivo_unico')],
            },
        ),
    ]
