# Generated by Django 6.1.1 on 2026-10-06 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_microsoft_crear_usuarios'),
        ('evaluaciones', '0035_consecutivo_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAsistente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente')], max_length=10)),
                ('contenido', models.TextField()),
                ('consultas', models.JSONField(blank=True, default=list)),
                ('fuentes', models.JSONField(blank=True, default=list)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='evaluaciones.conversacionasistente')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
