# Generated by Django 6.1.1 on 2026-10-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0037_asistente_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionasistente',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='evaluaciones.evaluacion'),
        ),
    ]
