# Generated by Django 6.1.1 on 2026-10-07 03:36

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_ops'),
        ('evaluaciones', '0038_asistente_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratacionOps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('contratista_nombre', models.CharField(max_length=200)),
                ('contratista_cedula', models.CharField(max_length=20)),
                ('exige_libreta', models.BooleanField(blank=True, null=True)),
                ('fecha_referencia', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('analizando', 'Analizando'), ('lista', 'Lista para revisar'), ('confirmada', 'Confirmada'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('decisiones', models.JSONField(blank=True, default=dict)),
                ('analisis_iniciado', models.DateTimeField(blank=True, null=True)),
                ('analizada_en', models.DateTimeField(blank=True, null=True)),
                ('segundos', models.FloatField(blank=True, null=True)),
                ('version_sistema', models.CharField(blank=True, max_length=40)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoOps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('entidad', 'De la entidad'), ('contratista', 'Del contratista')], max_length=20)),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_documento_ops)),
                ('tamano', models.BigIntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('contratacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='evaluaciones.contratacionops')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['origen', 'nombre_original'],
            },
        ),
        migrations.CreateModel(
            name='TablaHonorariosOps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vigencia', models.PositiveSmallIntegerField()),
                ('norma', models.CharField(blank=True, max_length=200)),
                ('profesional', models.JSONField(default=list)),
                ('reconocimiento', models.JSONField(blank=True, default=list)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('actualizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-vigencia'],
                'constraints': [models.UniqueConstraint(fields=('entidad', 'vigencia'), name='tabla_honorarios_unica_por_vigencia')],
            },
        ),
    ]
