# Generated by Django 6.1.1 on 2026-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0040_ops_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionops',
            name='documentos_eliminados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
