# Generated by Django 6.1.1 on 2026-10-08 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auditoria_sin_truncate'),
        ('evaluaciones', '0041_ops_retencion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='traslado', serialize=False, to='evaluaciones.evaluacion')),
                ('publicado_en', models.DateField()),
                ('dias_habiles', models.PositiveSmallIntegerField()),
                ('vence_en', models.DateField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionInforme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consecutivo', models.PositiveIntegerField()),
                ('observante', models.CharField(max_length=300)),
                ('requisito', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recibida_en', models.DateField()),
                ('texto', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pendiente', 'Pendiente de respuesta'), ('acoge', 'Se acoge'), ('acoge_parcial', 'Se acoge parcialmente'), ('no_acoge', 'No se acoge')], default='pendiente', max_length=20)),
                ('modifica_resultado', models.BooleanField(default=False)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='evaluaciones.proponente')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['consecutivo'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'consecutivo'), name='observacion_consecutivo_unico')],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoSubsanacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consecutivo', models.PositiveIntegerField()),
                ('requisitos', models.JSONField(blank=True, default=list)),
                ('descripcion', models.TextField()),
                ('enviado_en', models.DateField()),
                ('vence_en', models.DateField()),
                ('respondido_en', models.DateField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente de respuesta'), ('subsanado', 'Subsanado'), ('no_subsanado', 'No subsanado')], default='pendiente', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsanaciones', to='evaluaciones.evaluacion')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsanaciones', to='evaluaciones.proponente')),
            ],
            options={
                'ordering': ['consecutivo'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'consecutivo'), name='subsanacion_consecutivo_unico')],
            },
        ),
    ]
