# Generated by Django 6.1.1 on 2026-10-08 04:03

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auditoria_sin_truncate'),
        ('evaluaciones', '0043_tramite_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorEconomico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('puntaje_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('presupuesto_oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tabla_metodos', models.CharField(default='vigentes', max_length=12)),
                ('trm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_trm', models.DateField(blank=True, null=True)),
                ('calificacion', models.JSONField(blank=True, null=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores_economicos', to='evaluaciones.proceso')),
            ],
            options={
                'ordering': ['orden', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='OfertaEconomica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_ofertado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('archivo', models.FileField(blank=True, max_length=300, upload_to=evaluaciones.models._ruta_oferta_economica)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('revision', models.JSONField(blank=True, default=dict)),
                ('valor_corregido', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado', models.CharField(default='valida', max_length=12)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('justificacion', models.CharField(blank=True, default='', max_length=12)),
                ('nota', models.TextField(blank=True)),
                ('corregido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='evaluaciones.factoreconomico')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_economicas', to='evaluaciones.proponente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='factoreconomico',
            constraint=models.UniqueConstraint(fields=('proceso', 'lote'), name='factor_economico_lote_unico'),
        ),
        migrations.AddConstraint(
            model_name='ofertaeconomica',
            constraint=models.UniqueConstraint(fields=('factor', 'proponente'), name='oferta_economica_unica'),
        ),
    ]
