# Generated by Django 6.1.1 on 2026-10-08 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auditoria_sin_truncate'),
        ('evaluaciones', '0045_factor_economico_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCoincidencias',
            fields=[
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coincidencias', serialize=False, to='evaluaciones.proceso')),
                ('resultado', models.JSONField(default=dict)),
                ('revisiones', models.JSONField(blank=True, default=dict)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('calculado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.entidad')),
            ],
        ),
    ]
