# Generated by Django 6.1.1 on 2026-10-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0047_coincidencias_rls'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requerimientosubsanacion',
            name='subsanacion_consecutivo_unico',
        ),
        migrations.DeleteModel(
            name='RequerimientoSubsanacion',
        ),
    ]
