# Generated by Django 6.1.1 on 2026-10-09 01:50

import django.db.models.deletion
import evaluaciones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_onedrive_autorizado'),
        ('evaluaciones', '0048_quitar_subsanaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionProceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120)),
                ('fecha_cierre', models.DateField()),
                ('carpeta_drive', models.CharField(blank=True, max_length=1000)),
                ('archivo', models.FileField(max_length=300, upload_to=evaluaciones.models._ruta_preparacion)),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('ofertas_subidas', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'En fila'), ('leyendo', 'Leyendo'), ('lista', 'Lista'), ('error', 'Con error')], default='pendiente', max_length=10)),
                ('etapa', models.CharField(blank=True, max_length=200)),
                ('progreso', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cuentas.entidad')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
